### ISSUE TITLE
Allow to use interface

### ISSUE THREAD

**Issue by thomas-illiet** [ahydrax/Hangfire.MissionControl#10]
Hello guys,

On my project, I use a divided project (server / dashboard) with a common project to share the definition of the job  interface.

Can you update the use of the [MissionLauncherAttribute](https://github.com/ahydrax/Hangfire.MissionControl/blob/master/src/Hangfire.MissionControl/MissionLauncherAttribute.cs) attribute, to be able to use it on the interface?

Kind regards,
Thomas

**Comment by thomas-illiet** [comment]
I create a new pull request : https://github.com/ahydrax/Hangfire.MissionControl/pull/11

**Comment by thomas-illiet** [comment]
Hey @ahydrax, can you check my PR please :)

**Comment by ahydrax** [comment]
Fixed in https://github.com/ahydrax/Hangfire.MissionControl/releases/tag/0.5.3

**Comment by thomas-illiet** [comment]
Thx :)
