### ISSUE TITLE
Protect mission page/endpoint

### ISSUE THREAD

**Issue by thomas-illiet** [ahydrax/Hangfire.MissionControl#12]
Hello @ahydrax,

Do you have any idea to protect mission control with the following configuration:

```csharp
app.UseHangfireDashboard("/hangfire", new DashboardOptions
{
    IsReadOnlyFunc = (DashboardContext context) => true
});
```

Kind regards
ThomaK

**Comment by ahydrax** [comment]
Hi @thomas-illiet,

Currently MissionControl doesn't respect `IsReadOnlyFunc` callback to check user rights. 
I'll look into it, thanks!

**Comment by ahydrax** [comment]
It turned out that `IsReadOnly` flag was added in Hangfire `v1.7.0` but MissionControl have been targeted for `1.6.x` versions.
I've raised `hangfire.core` version and added new dashboard feature support.
You'll find new version here: https://www.nuget.org/packages/Hangfire.MissionControl/0.6.0

**Comment by thomas-illiet** [comment]
Your Rox !
