### ISSUE TITLE
Hide code-snippet from Mission Overview Page

### ISSUE THREAD

**Issue by lvdiev** [ahydrax/Hangfire.MissionControl#13]
Hello,

Is it possible to hide code-snippet from Mission Over View Page? I found it not help so much when reading the usings and namespaces. In other hand, it shows my code to the user.

Thanks.

**Comment by ahydrax** [comment]
hi @lvdiev , sounds reasonable, I'll try to figure out what to do

**Comment by ahydrax** [comment]
@lvdiev the update is live
https://www.nuget.org/packages/Hangfire.MissionControl/0.8.0
https://github.com/ahydrax/Hangfire.MissionControl/releases/tag/0.8.0
