### ISSUE TITLE
Cross-site Scripting Vulnerability in Hangfire.Core < v1.7.3

### ISSUE THREAD

**Issue by jasel-lewis** [ahydrax/Hangfire.MissionControl#14]
I respectfully request that `Hangfire.MissionControl` be updated to require a minimum version of v1.7.3 of `Hangfire.Core` as previous versions [contained an XSS vulnerability](https://github.com/HangfireIO/Hangfire/issues/1441). Currently, `Hangfire.MissionControl.csproj` allows for versions 1.7 up to, but not including, 1.8 (`<PackageReference Include="Hangfire.Core" Version="[1.7, 1.8)" />`).

I would be more than happy to create a Pull Request for this, however the `Hangfire.MissionControl.Tests.Web` package requires `net6.0` and we are locked-down to VS2019 at work. I cannot, in good conscience, just change the minimum version number of `Hangfire.Core` within the `Hangfire.MissionControl` project without the ability to run the tests before submitting the PR.

Henceforth, this Issue request for another contributor to do so.

Thank you.

**Comment by ahydrax** [comment]
Hi @jasel-lewis , thank you for letting me know that! I'll look into it ASAP

**Comment by jasel-lewis** [comment]
Great! Thank you, @ahydrax...

**Comment by ahydrax** [comment]
Closed in https://www.nuget.org/packages/Hangfire.MissionControl/0.8.1
