### ISSUE TITLE
Allow creating Missions without Attributes

### ISSUE THREAD

**Issue by wertzui** [ahydrax/Hangfire.MissionControl#15]
Instead of having to declare a lot of missions manually through attributes, I would like to create missions by passing in a collection of `Mission` objects into the `UseMissionControl` extension method.

That way I could build my own logic on how to define missions which would integrate into our code that we are already using for defining jobs.

For that to work, `UseMissionControl` would neet to get another overload that takes in an `IEnumerable<Mission>` which the existion method could call after it got those from the `MissionMapBuilder`.
The `Mission` class would need to be made `public` and get another constructor that does not rely on `Attribute`s, but just has a bunch of parameters to set everything directly.

**Comment by ahydrax** [comment]
Hi @wertzui. Thanks for the idea! Could you provide some examples how that API could look like?

**Comment by wertzui** [comment]
I've created a PR #16  to show how the API will look like.
A user can create a `Dictionary<string, Mission>` on his own, using the new constructors of `Mission`.
He can then pass this dictionary on to one of the new extension methods in `MissionControlBuilderExtensions`.

**Comment by ahydrax** [comment]
Thanks! I'll look into it

**Comment by wertzui** [comment]
Have you been able to look into it?
Please let me know if you find any issues that prevent merging.

**Comment by ahydrax** [comment]
hi @wertzui ! Sorry for a long delay, gonna get back from vacation next week

**Comment by wertzui** [comment]
Any update on this?

**Comment by ahydrax** [comment]
Merged
