### ISSUE TITLE
Javascript blocked when using x-content-type-options nosniff is enabled

### ISSUE THREAD

**Issue by Bchir** [ahydrax/Hangfire.MissionControl#5]
Hello, 
Javascript blocked when using x-content-type-options nosniff is enabled, a fix for it is to replace the obsolete mime type "text/javascript" by "application/javascript" on script tags

**Comment by ahydrax** [comment]
Hi there, thank you for that, I'll look into it.

**Comment by Bchir** [comment]
![image](https://user-images.githubusercontent.com/24528563/103866263-cba06d00-50c5-11eb-9951-35dc64c66ee6.png)
![image](https://user-images.githubusercontent.com/24528563/103866288-d65b0200-50c5-11eb-986e-80eabcb4e2a9.png)
![image](https://user-images.githubusercontent.com/24528563/103866393-fee2fc00-50c5-11eb-912d-8de0ac14c7a3.png)

**Comment by ahydrax** [comment]
Fixed in https://github.com/ahydrax/Hangfire.MissionControl/releases/tag/0.5.0
