### ISSUE TITLE
Unsupported CancellationToken and PerformContext 

### ISSUE THREAD

**Issue by EdoardoTona** [ahydrax/Hangfire.MissionControl#8]
The parameters CancellationToken and PerformContext are handled by hangfire but the UI of this extension requires to fill them

**Comment by ahydrax** [comment]
Will look into it, thanks

**Comment by ahydrax** [comment]
As far as I understood this should help you:
https://github.com/ahydrax/Hangfire.MissionControl/releases/tag/0.5.2
https://www.nuget.org/packages/Hangfire.MissionControl/0.5.2
